============================= test session starts ==============================
platform linux -- Python 3.10.5, pytest-7.4.2, pluggy-1.3.0
rootdir: /home/nicoboco/vscode/projeto-integrador
plugins: anyio-3.6.2
collected 12 items

tests/test_compradores.py .....                                          [ 41%]
tests/test_fornecedores.py .....                                         [ 83%]
tests/test_insumos.py .F                                                 [100%]

=================================== FAILURES ===================================
_______________________________ test_get_insumos _______________________________

    def test_get_insumos():
        res = client.get('/insumos/busca')
>       assert res.json()['mensagem'][0]['nome'] == 'Cobre'
E       KeyError: 'nome'

tests/test_insumos.py:24: KeyError
------------------------------ Captured log call -------------------------------
INFO     sqlalchemy.engine.Engine:base.py:1027 BEGIN (implicit)
INFO     sqlalchemy.engine.Engine:base.py:1853 SELECT tb_insumos.id AS tb_insumos_id, tb_insumos.id_fornecedor AS tb_insumos_id_fornecedor, tb_insumos.nome_insumo AS tb_insumos_nome_insumo, tb_insumos.created_at AS tb_insumos_created_at, tb_insumos.updated_at AS tb_insumos_updated_at 
FROM tb_insumos 
 LIMIT %(param_1)s, %(param_2)s
INFO     sqlalchemy.engine.Engine:base.py:1858 [generated in 0.00014s] {'param_1': 0, 'param_2': 10}
INFO     sqlalchemy.engine.Engine:base.py:1055 ROLLBACK
=============================== warnings summary ===============================
src/models/models.py:41
  /home/nicoboco/vscode/projeto-integrador/tests/../src/models/models.py:41: SAWarning: Can't validate argument 'passive_deletes'; can't locate any SQLAlchemy dialect named 'passive'
    class Vendas(Base):

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/test_insumos.py::test_get_insumos - KeyError: 'nome'
=================== 1 failed, 11 passed, 1 warning in 3.91s ====================
============================= test session starts ==============================
platform linux -- Python 3.10.5, pytest-7.4.2, pluggy-1.3.0
rootdir: /home/nicoboco/vscode/projeto-integrador
plugins: anyio-3.6.2
collected 13 items

tests/test_compradores.py .....                                          [ 38%]
tests/test_fornecedores.py .....                                         [ 76%]
tests/test_insumos.py ..F                                                [100%]

=================================== FAILURES ===================================
____________________________ test_get_insumos_by_id ____________________________

    def test_get_insumos_by_id():
        id = get_id('insumos')
        res = client.get(f'/insumos/busca/{id}')
>       assert res.json() == 'Cobre'
E       AssertionError: assert {'mensagem': {'created_at': '2023-10-01T22:23:15', 'id': 1332484248, 'id_fornecedor': 2194647005, 'nome_insumo': 'Cobre', ...}, 'status': 200} == 'Cobre'
E        +  where {'mensagem': {'created_at': '2023-10-01T22:23:15', 'id': 1332484248, 'id_fornecedor': 2194647005, 'nome_insumo': 'Cobre', ...}, 'status': 200} = <bound method Response.json of <Response [200 OK]>>()
E        +    where <bound method Response.json of <Response [200 OK]>> = <Response [200 OK]>.json

tests/test_insumos.py:29: AssertionError
------------------------------ Captured log call -------------------------------
INFO     sqlalchemy.engine.Engine:base.py:1027 BEGIN (implicit)
INFO     sqlalchemy.engine.Engine:base.py:1853 SELECT tb_insumos.id AS tb_insumos_id, tb_insumos.id_fornecedor AS tb_insumos_id_fornecedor, tb_insumos.nome_insumo AS tb_insumos_nome_insumo, tb_insumos.created_at AS tb_insumos_created_at, tb_insumos.updated_at AS tb_insumos_updated_at 
FROM tb_insumos 
 LIMIT %(param_1)s, %(param_2)s
INFO     sqlalchemy.engine.Engine:base.py:1858 [cached since 0.02713s ago] {'param_1': 0, 'param_2': 10}
INFO     sqlalchemy.engine.Engine:base.py:1055 ROLLBACK
INFO     sqlalchemy.engine.Engine:base.py:1027 BEGIN (implicit)
INFO     sqlalchemy.engine.Engine:base.py:1853 SELECT tb_insumos.id AS tb_insumos_id, tb_insumos.id_fornecedor AS tb_insumos_id_fornecedor, tb_insumos.nome_insumo AS tb_insumos_nome_insumo, tb_insumos.created_at AS tb_insumos_created_at, tb_insumos.updated_at AS tb_insumos_updated_at 
FROM tb_insumos 
WHERE tb_insumos.id = %(id_1)s 
 LIMIT %(param_1)s
INFO     sqlalchemy.engine.Engine:base.py:1858 [generated in 0.00052s] {'id_1': 1332484248, 'param_1': 1}
INFO     sqlalchemy.engine.Engine:base.py:1055 ROLLBACK
=============================== warnings summary ===============================
src/models/models.py:41
  /home/nicoboco/vscode/projeto-integrador/tests/../src/models/models.py:41: SAWarning: Can't validate argument 'passive_deletes'; can't locate any SQLAlchemy dialect named 'passive'
    class Vendas(Base):

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/test_insumos.py::test_get_insumos_by_id - AssertionError: assert...
=================== 1 failed, 12 passed, 1 warning in 3.57s ====================
============================= test session starts ==============================
platform linux -- Python 3.10.5, pytest-7.4.2, pluggy-1.3.0
rootdir: /home/nicoboco/vscode/projeto-integrador
plugins: anyio-3.6.2
collected 14 items

tests/test_compradores.py .....                                          [ 35%]
tests/test_fornecedores.py .....                                         [ 71%]
tests/test_insumos.py ...F                                               [100%]

=================================== FAILURES ===================================
_____________________________ test_update_insumos ______________________________

    def test_update_insumos():
>       id = get_id('insumo')

tests/test_insumos.py:32: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

schema = 'insumo'

    def get_id(schema: str):
        data = client.get(f'/{schema}/busca')
>       id = data.json()['mensagem'][0]['id']
E       KeyError: 'mensagem'

tests/test_insumos.py:12: KeyError
=============================== warnings summary ===============================
src/models/models.py:41
  /home/nicoboco/vscode/projeto-integrador/tests/../src/models/models.py:41: SAWarning: Can't validate argument 'passive_deletes'; can't locate any SQLAlchemy dialect named 'passive'
    class Vendas(Base):

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/test_insumos.py::test_update_insumos - KeyError: 'mensagem'
=================== 1 failed, 13 passed, 1 warning in 3.85s ====================
============================= test session starts ==============================
platform linux -- Python 3.10.5, pytest-7.4.2, pluggy-1.3.0
rootdir: /home/nicoboco/vscode/projeto-integrador
plugins: anyio-3.6.2
collected 14 items

tests/test_compradores.py .....                                          [ 35%]
tests/test_fornecedores.py .....                                         [ 71%]
tests/test_insumos.py ...F                                               [100%]

=================================== FAILURES ===================================
_____________________________ test_update_insumos ______________________________

    def test_update_insumos():
>       id = get_id('insumo')

tests/test_insumos.py:32: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

schema = 'insumo'

    def get_id(schema: str):
        data = client.get(f'/{schema}/busca')
>       id = data.json()['mensagem'][0]['id']
E       KeyError: 'mensagem'

tests/test_insumos.py:12: KeyError
=============================== warnings summary ===============================
src/models/models.py:41
  /home/nicoboco/vscode/projeto-integrador/tests/../src/models/models.py:41: SAWarning: Can't validate argument 'passive_deletes'; can't locate any SQLAlchemy dialect named 'passive'
    class Vendas(Base):

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/test_insumos.py::test_update_insumos - KeyError: 'mensagem'
=================== 1 failed, 13 passed, 1 warning in 3.65s ====================
============================= test session starts ==============================
platform linux -- Python 3.10.5, pytest-7.4.2, pluggy-1.3.0
rootdir: /home/nicoboco/vscode/projeto-integrador
plugins: anyio-3.6.2
collected 14 items

tests/test_compradores.py .....                                          [ 35%]
tests/test_fornecedores.py .....                                         [ 71%]
tests/test_insumos.py ...F                                               [100%]

=================================== FAILURES ===================================
_____________________________ test_update_insumos ______________________________

    def test_update_insumos():
        id = get_id('insumos')
    
        insumo = {'nome_insumo': 'Ferro'}
        res = client.put(f'/insumos/atualiza/{id}', json=insumo)
    
>       assert res.json()['status'] == 204
E       KeyError: 'status'

tests/test_insumos.py:37: KeyError
------------------------------ Captured log call -------------------------------
INFO     sqlalchemy.engine.Engine:base.py:1027 BEGIN (implicit)
INFO     sqlalchemy.engine.Engine:base.py:1853 SELECT tb_insumos.id AS tb_insumos_id, tb_insumos.id_fornecedor AS tb_insumos_id_fornecedor, tb_insumos.nome_insumo AS tb_insumos_nome_insumo, tb_insumos.created_at AS tb_insumos_created_at, tb_insumos.updated_at AS tb_insumos_updated_at 
FROM tb_insumos 
 LIMIT %(param_1)s, %(param_2)s
INFO     sqlalchemy.engine.Engine:base.py:1858 [cached since 0.05964s ago] {'param_1': 0, 'param_2': 10}
INFO     sqlalchemy.engine.Engine:base.py:1055 ROLLBACK
=============================== warnings summary ===============================
src/models/models.py:41
  /home/nicoboco/vscode/projeto-integrador/tests/../src/models/models.py:41: SAWarning: Can't validate argument 'passive_deletes'; can't locate any SQLAlchemy dialect named 'passive'
    class Vendas(Base):

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/test_insumos.py::test_update_insumos - KeyError: 'status'
=================== 1 failed, 13 passed, 1 warning in 4.40s ====================
============================= test session starts ==============================
platform linux -- Python 3.10.5, pytest-7.4.2, pluggy-1.3.0
rootdir: /home/nicoboco/vscode/projeto-integrador
plugins: anyio-3.6.2
collected 15 items

tests/test_compradores.py .....                                          [ 33%]
tests/test_fornecedores.py .....                                         [ 66%]
tests/test_insumos.py ....F                                              [100%]

=================================== FAILURES ===================================
_____________________________ test_delete_insumos ______________________________

    def test_delete_insumos():
>       id = get_id()
E       TypeError: get_id() missing 1 required positional argument: 'schema'

tests/test_insumos.py:41: TypeError
=============================== warnings summary ===============================
src/models/models.py:41
  /home/nicoboco/vscode/projeto-integrador/tests/../src/models/models.py:41: SAWarning: Can't validate argument 'passive_deletes'; can't locate any SQLAlchemy dialect named 'passive'
    class Vendas(Base):

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/test_insumos.py::test_delete_insumos - TypeError: get_id() missi...
=================== 1 failed, 14 passed, 1 warning in 4.83s ====================
